### ISSUE TITLE
High frequencies of AD rare variants

### ISSUE THREAD

**Issue by ashamehta** [HudsonAlpha/UDN_SV_export#2]
Hi,
I’m a bioinformatics masters student working at the Stanford UDN, and I’ve been looking at the frequencies of SVs that have been identified as causal in Stanford UDN patients. While most of them are low as expected (~.001), one has a total frequency of 0.16 and another has a total frequency of 0.67. The former is higher than expected, and the latter doesn’t seem to be possible.

Here are the variants with these frequencies:
chr12:25956617
DEL
autosomal dominant
HETCOUNT=265;HOMCOUNT=0
frequency=0.16

chr6:157468332
DUP:TANDEM
autosomal dominant
HETCOUNT=1102;HOMCOUNT=5
frequency=0.67

How are these frequencies possible for autosomal dominant pathogenic rare variants?

Thank you in advance for your clarification and for releasing this data!

**Comment by holtjma** [comment]
The short answer is _probably_ one of two things:

1. the variant isn't actually AD pathogenic
2. the frequency isn't actually that high

For the first point, let me first say I haven't researched the variants you linked at all.  However, CNV/SV databases are riddled with errors.  It is entirely possible that these variants are not actually AD _or_ pathogenic, but have been mislabeled as such because someone didn't have access to a database of population frequencies or just didn't do enough validation of the variant effects.  

For the second point, you need to remember that this is a raw call set.  These variants have not been verified (see [Limitations](https://github.com/HudsonAlpha/UDN_SV_export#limitations)) and an estimated 50% of them are probably false positives.  Additionally, many false positives are caused by artifacts from sequencing and/or the process, and those false positives tend to be called in multiple samples due to those artifacts.  We know of at least a couple variants that have been called in dozens of samples, are almost always a false positive, but is a true positive and definitively pathogenic variant in at least one sample that has been through an identical process.  The bottom line is that CNV calling is extremely messy and riddled with false positives as well simply due to the state of our calling software.

A few steps I would recommend:
1. Verify that these variants are definitely real in your patient
2. Verify that the annotations you have on said variant are high confidence with good supporting data
3. Check for reasons that the variant might get called frequently as a false positive: low complexity sequence, high homology add the breakpoints, etc.

**Comment by ashamehta** [comment]
This makes sense. I was thinking that because similar variant calls had not been consolidated that the frequency would be underestimated, rather than overestimated, but I was not considering the high false positive rate. 

Thanks so much for your insight.
